-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-07-28 13:05:57 COT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
-- Converted to PostgreSQL

-- Crear todas las tablas primero
CREATE TABLE crm_miembros (
    id_miembro VARCHAR(12),
    edad INTEGER,
    rango_edad VARCHAR(100),
    genero VARCHAR(100),
    pais VARCHAR(100),
    ciudad VARCHAR(100),
    activo BOOLEAN
);

CREATE TABLE mstr_proveedores (
    id_proveedor VARCHAR(12),
    nombre_proveedor VARCHAR(100),
    pais VARCHAR(100),
    ciudad VARCHAR(100),
    centro_distribucion VARCHAR(100),
    email VARCHAR(100),
    telefono VARCHAR(100),
    calificacion NUMERIC(2, 1),
    activo BOOLEAN
);

CREATE TABLE mstr_tiendas (
    id_tienda VARCHAR(12),
    tipo_tienda VARCHAR(50),
    pais VARCHAR(100),
    ciudad VARCHAR(100),
    centro_distribucion VARCHAR(100),
    activa BOOLEAN
);

CREATE TABLE mstr_articulos (
    id_articulo VARCHAR(12),
    nombre_producto VARCHAR(100),
    categoria VARCHAR(100),
    sku VARCHAR(100),
    codigo_barras VARCHAR(100),
    precio NUMERIC(10, 2),
    activo BOOLEAN,
    mstr_proveedores_id_proveedor VARCHAR(12)
);

CREATE TABLE fact_ventas (
    id_venta VARCHAR(12),
    fecha_hora TIMESTAMP,
    id_miembro VARCHAR(12),
    id_articulo VARCHAR(12),
    id_tienda VARCHAR(12),
    canal VARCHAR(100),
    tipo_pago VARCHAR(50),
    descuento NUMERIC(5, 2),
    precio NUMERIC(12, 2)
);

CREATE TABLE fact_devoluciones (
    id_venta VARCHAR(12),
    estado VARCHAR(100),
    motivo VARCHAR(100)
);

CREATE TABLE inv_stock_diario (
    stock_minimo INTEGER,
    stock_maximo INTEGER,
    stock_fisico INTEGER,
    id_tienda VARCHAR(12),
    id_articulo VARCHAR(12)
);

-- Agregar todas las Primary Keys
ALTER TABLE crm_miembros
ADD CONSTRAINT crm_miembros_PK PRIMARY KEY (id_miembro);

ALTER TABLE mstr_proveedores
ADD CONSTRAINT mstr_proveedores_PK PRIMARY KEY (id_proveedor);

ALTER TABLE mstr_tiendas
ADD CONSTRAINT mstr_tiendas_PK PRIMARY KEY (id_tienda);

ALTER TABLE mstr_articulos
ADD CONSTRAINT mstr_articulos_PK PRIMARY KEY (id_articulo);

ALTER TABLE fact_ventas
ADD CONSTRAINT fact_ventas_PK PRIMARY KEY (id_venta);

ALTER TABLE fact_devoluciones
ADD CONSTRAINT fact_devoluciones_PK PRIMARY KEY (id_venta);

ALTER TABLE inv_stock_diario
ADD CONSTRAINT inv_stock_diario_PK PRIMARY KEY (id_tienda, id_articulo);

-- Agregar todas las Foreign Keys
ALTER TABLE mstr_articulos
ADD CONSTRAINT fk_mstr_articulos_proveedores FOREIGN KEY (mstr_proveedores_id_proveedor) REFERENCES mstr_proveedores (id_proveedor);

ALTER TABLE fact_ventas
ADD CONSTRAINT fk_fact_ventas_articulos FOREIGN KEY (id_articulo) REFERENCES mstr_articulos (id_articulo);

ALTER TABLE fact_ventas
ADD CONSTRAINT fk_fact_ventas_miembros FOREIGN KEY (id_miembro) REFERENCES crm_miembros (id_miembro);

ALTER TABLE fact_ventas
ADD CONSTRAINT fk_fact_ventas_tiendas FOREIGN KEY (id_tienda) REFERENCES mstr_tiendas (id_tienda);

ALTER TABLE inv_stock_diario
ADD CONSTRAINT fk_inv_stock_articulo FOREIGN KEY (id_articulo) REFERENCES mstr_articulos (id_articulo);

ALTER TABLE inv_stock_diario
ADD CONSTRAINT fk_inv_stock_tienda FOREIGN KEY (id_tienda) REFERENCES mstr_tiendas (id_tienda);